// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvvtC3tRYYRaY2b39EpVPRoaqdcXZY8g0',
    appId: '1:182272150880:web:f64e6758b287f8d3d12205',
    messagingSenderId: '182272150880',
    projectId: 'skibidi-mewing-ohio-tax',
    authDomain: 'skibidi-mewing-ohio-tax.firebaseapp.com',
    storageBucket: 'skibidi-mewing-ohio-tax.appspot.com',
    measurementId: 'G-6H18NEFJP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwaXZrutVWVOAo-8rg9sc1u-l3y1ZwpQg',
    appId: '1:182272150880:android:a6d97166fa3681f7d12205',
    messagingSenderId: '182272150880',
    projectId: 'skibidi-mewing-ohio-tax',
    storageBucket: 'skibidi-mewing-ohio-tax.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuwxyG-6ak4-MlQq4E-D_ZY0m7D9zgRP0',
    appId: '1:182272150880:ios:28f9b743c52b6c34d12205',
    messagingSenderId: '182272150880',
    projectId: 'skibidi-mewing-ohio-tax',
    storageBucket: 'skibidi-mewing-ohio-tax.appspot.com',
    iosClientId: '182272150880-c9ift1k3cp4chl84jer7c8ka9gupakkj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gooningsigmamalerizzdukedennisrizzlratiobetaskibidiwithkaicenatinohio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuwxyG-6ak4-MlQq4E-D_ZY0m7D9zgRP0',
    appId: '1:182272150880:ios:28f9b743c52b6c34d12205',
    messagingSenderId: '182272150880',
    projectId: 'skibidi-mewing-ohio-tax',
    storageBucket: 'skibidi-mewing-ohio-tax.appspot.com',
    iosClientId: '182272150880-c9ift1k3cp4chl84jer7c8ka9gupakkj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gooningsigmamalerizzdukedennisrizzlratiobetaskibidiwithkaicenatinohio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvvtC3tRYYRaY2b39EpVPRoaqdcXZY8g0',
    appId: '1:182272150880:web:b55748f4beb81ca3d12205',
    messagingSenderId: '182272150880',
    projectId: 'skibidi-mewing-ohio-tax',
    authDomain: 'skibidi-mewing-ohio-tax.firebaseapp.com',
    storageBucket: 'skibidi-mewing-ohio-tax.appspot.com',
    measurementId: 'G-LJ8ZD0ZLFL',
  );

}